shore-gmbh/payment-connector

lib/tss/connector.rb
spec/tss/connector_spec.rb

F support 'create organization' request

---

lib/tss/connector.rb

C improve inline documentation

---

lib/tss/connector.rb
spec/tss/connector_spec.rb

F [#TSS-10] Fix how query parameters are passed to GET /v1/organizations

---

lib/tss/connector.rb
lib/tss/organization_connector.rb
lib/tss/response_handlers.rb
spec/tss/organization_connector_spec.rb

- also introduce handle_put_request

F [PS-16] support for /v1/organizations/:oid/stripe

---

lib/tss/organization_connector.rb
lib/tss/version.rb
spec/tss/organization_connector_spec.rb

F [#PS-11] Add connector methods for charges

---

spec/spec_helper.rb

Fix tests for payment-connector

---

README.md

C add travis badge in readme

---

lib/tss/organization_connector.rb
spec/tss/organization_connector_spec.rb

Minor changes to names and changing structure of answer for post create charge request

---

lib/tss/organization_connector.rb
lib/tss/version.rb
spec/tss/organization_connector_spec.rb

Return asnwer with root key 'created_charge' when creating a charge

---

README.md
lib/payment-connector.rb
lib/payment/config.rb
lib/payment/connector.rb
lib/payment/http_retriever.rb
lib/payment/organization_connector.rb
lib/payment/response_handlers.rb
lib/payment/version.rb
payment-connector.gemspec
spec/payment/config_spec.rb
spec/payment/connector_spec.rb
spec/payment/organization_connector_spec.rb
spec/spec_helper.rb

Renames the top-level namespace. I want to do this, before we merge our branch in Core into `master`. PR for the Core project to integrate the rename coming once this is merged...
ping @ceigel

C renames in the code: TSS => ShorePayment

---

lib/payment/organization_connector.rb
spec/payment/organization_connector_spec.rb

F [#COR-938] Add pagination parameters for get_charges

---

lib/payment/organization_connector.rb
spec/payment/organization_connector_spec.rb

F [#COR-938] Change perPage to per_page

---

lib/payment/organization_connector.rb
lib/payment/version.rb

Allow get_charges to receive filter and order parameters

---

lib/payment/version.rb

Upgrade payment connector

---

lib/payment/version.rb

F [#COR-986] Add statement-descriptor to charge creation

---

lib/payment/merchant_stripe.rb
spec/payment/merchant_stripe_spec.rb

https://shore.myjetbrains.com/youtrack/issue/PS-44#

F [#PS-44] add get_dispute method to MerchantPayment

---

lib/payment/merchant_stripe.rb
spec/payment/merchant_stripe_spec.rb
spec/support/stripe_payment.rb

New attributes:
* legal_entity.business_name
* legal_entity.business_tax_id
* legal_entity.additional_owners[].address
* legal_entity.additional_owners[].verification
* legal_entity.verification

F [#PS-56] add Verification class, introduce new attrs to legal_entiy

---

README.md
lib/payment/all.rb
lib/payment/connector.rb
lib/payment/merchant_connector.rb
lib/payment/response_classes/dispute.rb
lib/payment/response_classes/merchant_stripe.rb
lib/payment/version.rb
spec/payment/connector_spec.rb
spec/payment/dispute_spec.rb
spec/payment/merchant_connector_spec.rb
spec/payment/merchant_stripe_spec.rb
spec/support/stripe_payment.rb

C [#PS-14] rename from organization to merchant

---

lib/payment/merchant_connector.rb
lib/payment/version.rb

Fix error string bug

---

lib/payment/merchant_connector.rb
spec/payment/merchant_connector_spec.rb

Remove duplicated parameter charge_id from refunds

---

lib/payment/merchant_connector.rb
spec/payment/merchant_connector_spec.rb

Return the entire response from payment service

---

lib/payment/merchant_connector.rb
lib/payment/response_classes/merchant_stripe.rb
spec/payment/merchant_connector_spec.rb

F [#PS-126] Add charge_limit for merchants

---

lib/payment/response_classes/merchant_stripe.rb
spec/payment/merchant_stripe_spec.rb

Fix issue PS-135. Charges key is kept in response

---

lib/payment/merchant_connector.rb
lib/payment/response_classes/merchant_stripe.rb
spec/payment/merchant_connector_spec.rb
spec/payment/merchant_stripe_spec.rb
spec/support/stripe_payment.rb

https://shore.myjetbrains.com/youtrack/issue/PS-136

F [#PS-136] add captured attribute to Charge

---

lib/payment/merchant_connector.rb
spec/payment/merchant_connector_spec.rb

https://shore.myjetbrains.com/youtrack/issue/PS-155

F [#PS-155] add update_charge method

---

lib/payment/merchant_connector.rb
spec/payment/merchant_connector_spec.rb

https://shore.myjetbrains.com/youtrack/issue/PS-137

F [#PS-137] add capture method

---

lib/payment/merchant_connector.rb
lib/payment/response_classes/merchant_stripe.rb
lib/payment/version.rb
spec/payment/merchant_connector_spec.rb
spec/payment/merchant_stripe_spec.rb

Remove for_appointment and unused appointment_id and customer_id from charge properties

---

lib/payment/merchant_connector.rb
lib/payment/version.rb
spec/payment/merchant_connector_spec.rb

Add deep-symbolize keys when checking charge creation parameters
